restaurant:
  closedDays: 2 # comma separated values, 1 - Sunday, 2 - Monday, ..., 7 - Saturday
  openHour: 9
  openMinute: 0
  closeHour: 16
  closeMinute: 30
  slotInMinutes: 30
  slotsPerReservation: 2
  restaurantCapacity: 8
  maxBookAheadDays: 14
  timezone: Europe/Amsterdam
  fromemail: reservations@heart-garden.nl
  oneHouseHoldLimitInForm: 2
  goLive: 2020-06-01
  guestTableNbMap:
    1: 1
    2: 1
    3: 2
    4: 2
    5: 3
    6: 3
    7: 4
    8: 4
