restaurant:
  closedDays: 2 # comma separated values, 1 - Sunday, 2 - Monday, ..., 7 - Saturday
  closedDates:
  reservationNotAllowed: # 7-11:00-14:00, 1-11:00-14:00
  openHour: 9
  openMinute: 0
  closeHour: 16
  closeMinute: 30
  slotInMinutes: 30
  slotsPerReservation: 2 # how many 30 minute slots are taken for a reservation
  restaurantCapacity: 10 # how many tables are there in the restaurant
  maxBookAheadDays: 14
  timezone: Europe/Amsterdam
  fromemail: reservations@heart-garden.nl
  oneHouseHoldLimitInForm: 2
  goLive: 2021-04-28
  guestTableNbMap: # how many tables are taken for a number of guests in one reservation: guest nb -> number of tables
    1: 1
    2: 1
    3: 2
    4: 2
    5: 3
    6: 3
    7: 4
    8: 4
